name: 'Hits of Code Bage'
description: 'Count hits of code and render a badge for display result'
inputs:
  before:
    description: 'Set the end date of hoc (YYYY-MM-DD). Default: now day'
    required: false
    default: '[]'
  dir:
    description: 'Directory to scan. Default: current directory'
    required: false
    default: '.'
  exclude:
    description: 'Glob pattern to exclude files/dirs, e.g. "vendor/**". No default value'
    required: false
    default: '[]'
  since:
    description: 'Set the start date of hoc (YYYY-MM-DD). Default: 2000-01-01'
    required: false
    default: '2000-01-01'
  output_dir:
    description: 'Output directory. Default: output'
    required: false
    default: 'output'
  filename:
    description: 'Output filename. Default: hoc-badge.svg'
    required: false
    default: 'hoc-badge.svg'
  rounding:
    description: 'Rounding mode. Default: I'
    required: false
    default: 'I'
  color:
    description: 'Background color. Default: green'
    required: false
    default: 'green'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1.172.0
      with:
        ruby-version: '3.3.0'
    - name: Generate badge
      run: |
        gem install hoc
        pip install anybadge
        $GITHUB_ACTION_PATH/generate-badge.sh \
          -b "$BEFORE" \
          -c "$COLOR" \
          -d "$DIR" \
          -e "$EXCLUDE" \
          -f "$FILENAME" \
          -o "$OUTPUT_DIR" \
          -r "$ROUNDING" \
          -s "$SINCE"
      shell: bash
      env:
        BEFORE:      ${{ inputs.before }}
        COLOR:       ${{ inputs.color }}
        DIR:         ${{ inputs.dir }}
        EXCLUDE:     ${{ inputs.exclude }}
        FILENAME:    ${{ inputs.filename }}
        OUTPUT_DIR:  ${{ inputs.output_dir }}
        ROUNDING:    ${{ inputs.rounding }}
        SINCE:       ${{ inputs.since }}

