on: [push]

jobs:

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master

  hits_counter_job:
    name: Generate and deploy HoC-badge
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          dir: .
          since: 2000-01-01
          output_dir: ./output
          filename: hits.svg
      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ github.token }}
