on: [push]

jobs:
  lines_counter_job:
    runs-on: ubuntu-latest
    name: A job to count lines of code
    steps:
      - uses: actions/checkout@v4
      - id: badge-generator
        uses: ./
        with:
          dir: '.'
          since: '2000-01-01'
