on: [push]

jobs:

  tests_job:
    name: Test scripts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
      - uses: articulate/actions-markdownlint@v1.1.0

  hits_counter_job:
    name: Generate and deploy HoC-badge
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          dir: .
          since: 2000-01-01
          output_dir: output-dir
          exclude: |
            .gitignore
            LICENSE
      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_dir: output-dir
          publish_branch: image-data
          github_token: ${{ github.token }}
